version: '3.8'

services:
  music-stems-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped